## Mean-Variance-Standard Deviation Calculator

In [1]:
import numpy as np

In [2]:
list = [0,1,2,3,4,5,6,7,8]

In [9]:
# Converter tipo de dados
ls = np.array(list)
ls

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [10]:
# Transformação do formato
ls = ls.reshape(3,3)
ls

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [12]:
calculations = {
    'mean': [np.mean(ls,axis=0), np.mean(ls,axis=1), np.mean(ls)],
    'variance': [np.var(ls,axis=0), np.var(ls,axis=1), np.var(ls)],
    'standard deviation': [np.std(ls,axis=0), np.std(ls,axis=1), np.std(ls)],
    'max': [np.max(ls,axis=0), np.max(ls,axis=1), np.max(ls)],
    'min': [np.min(ls,axis=0), np.min(ls,axis=1), np.min(ls)],
    'sum': [np.sum(ls,axis=0), np.sum(ls,axis=1), np.sum(ls)]
}
calculations

{'mean': [array([3., 4., 5.]), array([1., 4., 7.]), 4.0],
 'variance': [array([6., 6., 6.]),
  array([0.66666667, 0.66666667, 0.66666667]),
  6.666666666666667],
 'standard deviation': [array([2.44948974, 2.44948974, 2.44948974]),
  array([0.81649658, 0.81649658, 0.81649658]),
  2.581988897471611],
 'max': [array([6, 7, 8]), array([2, 5, 8]), 8],
 'min': [array([0, 1, 2]), array([0, 3, 6]), 0],
 'sum': [array([ 9, 12, 15]), array([ 3, 12, 21]), 36]}